### ISSUE TITLE
Support partial input data

### ISSUE THREAD

**Issue by JohnDMcMaster** [SiliconAnalysis/pr0nmap#7]
Sometimes very large stitches can't be completed easily, but portions can be stitched. I think this was supported in the past but doesn't seem to currently work. Example output:

```
WARNING: got exception trying supertile subtile
Traceback (most recent call last):
  File "/home/mcmaster/doc/ext/pr0nmap/pr0nmap/tile.py", line 222, in run
    taskers[task](args)
  File "/home/mcmaster/doc/ext/pr0nmap/pr0nmap/tile.py", line 214, in task_subtile
    self.task_subtile(args)
  File "/home/mcmaster/doc/ext/pr0nmap/pr0nmap/tile.py", line 193, in task_subtile
    tw=self.tw, th=self.th)
  File "/home/mcmaster/doc/ext/pr0nmap/pr0nmap/pimage.py", line 376, in from_fns
    ret = Image.new(mode, (width, height))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2024, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: argument 1 must be string, not None
```

**Comment by JohnDMcMaster** [comment]
fixed
